library(tools)
source(file_path_as_absolute("functions.R"))


library(caret)
library(mlbench)


load("2110/rdas/compare22.RData")
importance <- varImp(twoGramEntidadesHoraErro, scale=FALSE)
# summarize importance
print(importance)
# plot importance
plot(importance, top = 30)


limpar()

limpar <- function() {
	rm("aspectos")
	rm("aspectosManter")
	rm("aspectosRemover")
	rm("dados")
	rm("dadosQ1")
	rm("data_test")
	rm("data_train")
	rm("dataFrameEntidades")
	rm("dataFrameEstabelecimento")
	rm("dataFrameGram")
	rm("dataFrameHash")
	rm("dataFrameTexto")
	rm("dbpediaTypesCompleto")
	rm("dbpediaTypesPageRank")
	rm("dtm_train_hash_tags")
	rm("dtm_train_texto")
	rm("maFinal")
	rm("matriz2Gram")
	rm("matriz2Gram25")
	rm("matriz2GramDBPedia")
	rm("matriz2GramEntidades")
	rm("matriz3Gram25")
	rm("matrizDBPediaCompleto")
	rm("matrizDBPediaTypesPage")
	rm("matrizThreeGram")
	rm("matrizTwoGram25Hora")
	rm("matrizTwoGramCateogoriaLocalizacao")
	rm("matrizTwoGramDBPediaSubject")
	rm("matrizTwoGramDiaSemana")
	rm("matrizTwoGramEntidades2")
	rm("matrizTwoGramEntidadesHora",,"matrizTwoGramErros")
	rm("matrizWikipedia")
	rm("threeGram")
	rm("treegram25")
	rm("twoGDBPedia")
	rm("twogram")
	rm("twogram25")
	rm("twoGram25Hora")
	rm("twoGramCategoriaLocalizacao")
	rm("twoGramDBPediaSubject")
	rm("twoGramDiaSemana")
	rm("twogramentidades")
	rm("twoGramEntidades25")
	rm("twoGramEntidadesHora", "twoGramErros")
	rm("vectorizerEstabelecimento")
	rm("vectorizerHashTags")
	rm("vocab")
	rm("vocabEstabelecimento")
	rm("vocabHashTags")
	rm("wikipediaCategory")
}